{% set name = "urdfdom" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ros/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 8f3d56b0cbc4b84436d8baf4c8346cd2ee7ffb257bba5ddd9892c41bf516edc4
  patches:
    - cmake.patch  # [win]
    - windows-install.patch
    - console_bridge_1_0.patch

build:
  number: 3
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - console_bridge
    - tinyxml
    - urdfdom_headers
  run:
    - console_bridge
    - tinyxml
    - urdfdom_headers

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - pkg-config --modversion {{ name }}  # [unix]
    - test -f $PREFIX/lib/lib{{ name }}_model${SHLIB_EXT}  # [unix]
    - if exist %PREFIX%\\Library\\CMake\\urdfdom-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: http://github.com/ros/urdfdom
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'URDF parser'
  dev_url: https://github.com/ros/urdfdom

extra:
  recipe-maintainers:
    - jcarpent
    - wolfv
    - lesteve
